### ISSUE TITLE
Q: Forgot to use the assignment template 

### ISSUE THREAD

**Issue by yzhanguvt** [janboone/Python-programming-for-economists#3]
Hi,

After I submitted the assignment, I realized that I didn't use the template. I tried to delete the uploaded file so I can upload a new one, but can't find a way to do it. I'm new to github so I'm not sure if there's a way to do it? Or whether to use the template is optional as long as my answer is easy to read?

Thank you.

**Comment by janboone** [comment]
I think we will be able to grade the file, so no need to worry.

Regards, Jan.
